/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
}
export interface ContactMessage {
  'id' : bigint,
  'date' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Event {
  'id' : bigint,
  'titleEnglish' : string,
  'titleHindi' : string,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'imageUrl' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAnnouncement' : ActorMethod<[string, string], bigint>,
  'addEvent' : ActorMethod<[string, string, Time, string, string], bigint>,
  'addGalleryItem' : ActorMethod<[string, string], bigint>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getContactMessage' : ActorMethod<[bigint], ContactMessage>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getGalleryItem' : ActorMethod<[bigint], GalleryItem>,
  'seedData' : ActorMethod<[], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];