/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'titleEnglish' : IDL.Text,
  'titleHindi' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getContactMessage' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Nat], [GalleryItem], ['query']),
  'seedData' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'titleEnglish' : IDL.Text,
    'titleHindi' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getContactMessage' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getGalleryItem' : IDL.Func([IDL.Nat], [GalleryItem], ['query']),
    'seedData' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };